### PR TITLE
Readme Usage Section Fixes

### PR DESCRIPTION
**Pull request by Shadorain**
# First
The usage section of README.md had some broken functions that I fixed to what they should be (are errors otherwise):
`rope_delete()` -> `rope_del()`
`rope_createcstr(rope *r, value)` -> `rope_create_cstr(rope *r)`
Added a `_rope_print(r)` line as well to show how to print the test ropes

# Second
Added some lines to make sure that they include the right file into their project (`rope.h`) and compile `rope.c` in as well.

# Third
Finally, I changed a good bit of the formatting, my markdown linter gets quite upset with 80+ characters in a line so I changed that and other little things.
Thank you, hope this helps!

### CODE REVIEW

**Comment by Shadorain** [comment]
I updated this to only have the usage section fixes and no styling changes in the Markdown!

**Comment by josephg** [comment]
Great - now I can read the PR.

So, more styling changes - why did you change the `//` comments to `/* */` comments in the documentation?

**Comment by Shadorain** [comment]
Awesome! 
I did this because only newer C standards (C99 and forward if I remember correctly) can read `//`.
If you don't like this then I can change that back as well!

**Comment by josephg** [comment]
Yes please - c99 was 22 years ago. It’s well supported. (And if it’s not supported by your compiler, this library won’t build anyway.)

Receiving a PR which changes style is like having a visitor rearrange the furniture in my home, or put up their own art on my walls. It always feels weird to be on the receiving end of that, and as well intentioned as they might be, I think I have to push back on principle.

**Comment by Shadorain** [comment]
For sure and honestly this was a learning experience for me too that if I'm making a PR that I should not be touching any subjective areas because that isn't mine to touch and I learned that the hard way and am grateful. I appreciate u giving the push back there because I wouldn't have learnt that!!

**Comment by josephg** [comment]
Cool - thanks for the PR!

**Pull request merged**
